import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/ui/Navbar";
import { ModalProvider } from "@/components/providers/modal-provider";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Licenciamento Gestotal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="flex h-screen">
          <NavBar />
          <main className="flex-1 flex flex-col justify-center items-center" style={{ backgroundColor: "#F9F7F7" }}>
            <ModalProvider />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
